### PR TITLE
Resolves #243

### LINKED ISSUE #243: Fix Project Create
The project create command is out of date with the API. Requires description and owner fields.

See below to reproduce.

```
prolific project create --title "Advent-Day-2" --workspace 6920f50a1be7bfb14646881a
Error: error: unable to fulfil request /api/v1/workspaces/6920f50a1be7bfb14646881a/projects/: request failed: map[description:[This field may not be blank.] owner:[This field may not be null.]]
Usage:
  prolific project create [flags]

Examples:

To create a project inside a workspace
$ prolific project create -t "Research into AI" -w 6261321e223a605c7a4f7564


Flags:
  -h, --help               help for create
  -t, --title string       The title of the project.
  -w, --workspace string   The ID of the workspace to create the project in.

Global Flags:
      --config string   config file (default is $HOME/.config/prolific-oss/prolific.yaml)

error: unable to fulfil request /api/v1/workspaces/6920f50a1be7bfb14646881a/projects/: request failed: map[description:[This field may not be blank.] owner:[This field may not be null.]]
```

### PR DESCRIPTION
**Pull request by SeanAlexanderHarris**
- Fixes create project command (includes owner and description field in create project command)
- Uses 'GetMe' to assign CLI user as project owner (no user passed option)
- Updated client command, tests, command help example

See example below
```
./prolific project create --title "testing" --workspace 12345f50a1be7bfb14646881b -d "testing fixing the create project command"

Created project: 692367e440a17c49250d084c
```

### CODE REVIEW

File: cmd/project/create_test.go [hunk 1]
```diff
@@ -65,17 +67,27 @@ func TestCreateCommandCreatesProject(t *testing.T) {
 	c := mock_client.NewMockAPI(ctrl)
 
 	r := client.CreateProjectResponse{}
+	userID := "user-123"
```
Comment (prolific-snyk) [inline cmd/project/create_test.go]: ### <sub></sub>&nbsp; Use of Hardcoded Credentials

Do not hardcode credentials in code. Found `hardcoded` credential used in `userID`.

<h6>
Line 70 | <a href="https://cwe.mitre.org/data/definitions/798.html">CWE-798</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 500</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1 - 2` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L70

</details>

File: cmd/project/create_test.go [hunk 2]
```diff
@@ -65,17 +67,27 @@ func TestCreateCommandCreatesProject(t *testing.T) {
...
+	description := "A test project"
 	record := model.Project{
 		ID:    "123123",
 		Title: "Titan",
 	}
 
+	c.
+		EXPECT().
+		GetMe().
+		Return(&client.MeResponse{ID: userID}, nil).
```
Comment (prolific-snyk) [inline cmd/project/create_test.go]: ### <sub></sub>&nbsp; Use of Hardcoded Credentials

Do not hardcode credentials in code. Found `hardcoded` credential used in `userID`.

<h6>
Line 82 | <a href="https://cwe.mitre.org/data/definitions/798.html">CWE-798</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 500</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L70

`Step 2` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L82

</details>

File: cmd/project/create_test.go [hunk 3]
```diff
@@ -65,17 +67,27 @@ func TestCreateCommandCreatesProject(t *testing.T) {
...
+		MaxTimes(1)
+
 	c.
 		EXPECT().
 		CreateProject(gomock.Eq(workspaceID), gomock.Eq(model.Project{
-			Title: record.Title,
+			Title:       record.Title,
+			Description: description,
+			Owner:       userID,
```
Comment (prolific-snyk) [inline cmd/project/create_test.go]: ### <sub></sub>&nbsp; Use of Hardcoded Credentials

Do not hardcode credentials in code. Found `hardcoded` credential used in `userID`.

<h6>
Line 90 | <a href="https://cwe.mitre.org/data/definitions/798.html">CWE-798</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 500</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L70

`Step 2` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L90

</details>

File: cmd/project/create_test.go [hunk 4]
```diff
@@ -110,17 +123,27 @@ func TestCreateCommandReturnsErrorIfCreateProjectFails(t *testing.T) {
 
 	errorMessage := "Unable to create project, because the flim flam is broken"
 	r := client.CreateProjectResponse{}
+	userID := "user-123"
```
Comment (prolific-snyk) [inline cmd/project/create_test.go]: ### <sub></sub>&nbsp; Use of Hardcoded Credentials

Do not hardcode credentials in code. Found `hardcoded` credential used in `userID`.

<h6>
Line 126 | <a href="https://cwe.mitre.org/data/definitions/798.html">CWE-798</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 500</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1 - 2` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L126

</details>

File: cmd/project/create_test.go [hunk 5]
```diff
@@ -110,17 +123,27 @@ func TestCreateCommandReturnsErrorIfCreateProjectFails(t *testing.T) {
...
+	description := "A test project"
 	record := model.Project{
 		ID:    "123123",
 		Title: "Titan",
 	}
 
+	c.
+		EXPECT().
+		GetMe().
+		Return(&client.MeResponse{ID: userID}, nil).
```
Comment (prolific-snyk) [inline cmd/project/create_test.go]: ### <sub></sub>&nbsp; Use of Hardcoded Credentials

Do not hardcode credentials in code. Found `hardcoded` credential used in `userID`.

<h6>
Line 138 | <a href="https://cwe.mitre.org/data/definitions/798.html">CWE-798</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 500</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L126

`Step 2` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L138

</details>

File: cmd/project/create_test.go [hunk 6]
```diff
@@ -110,17 +123,27 @@ func TestCreateCommandReturnsErrorIfCreateProjectFails(t *testing.T) {
...
+		MaxTimes(1)
+
 	c.
 		EXPECT().
 		CreateProject(gomock.Eq(workspaceID), gomock.Eq(model.Project{
-			Title: record.Title,
+			Title:       record.Title,
+			Description: description,
+			Owner:       userID,
```
Comment (prolific-snyk) [inline cmd/project/create_test.go]: ### <sub></sub>&nbsp; Use of Hardcoded Credentials

Do not hardcode credentials in code. Found `hardcoded` credential used in `userID`.

<h6>
Line 146 | <a href="https://cwe.mitre.org/data/definitions/798.html">CWE-798</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 500</a> | <a href="https://learn.snyk.io/lesson/hardcoded-secrets/">Learn more about this vulnerability</h6>

<details>

<summary>Data flow: 2 steps</summary>

`Step 1` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L126

`Step 2` https://github.com/prolific-oss/cli/blob/174978cdf203900e88032e5aaf56e57adf6db17d/cmd/project/create_test.go#L146

</details>

**Comment by script-this** [comment]
@SeanAlexanderHarris changes look fine, just the snyk issue to handle.
